server.port=8083
spring.application.name=api-gateway

spring.config.import=optional:file:.env[.properties]

# Rota HTTP para o Auth Server
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Rota WebSocket para o Auth Server
# IMPORTANTE: ws:// é obrigatório para o Gateway fazer o upgrade de protocolo.
# Com http:// o handshake WebSocket falha silenciosamente.
spring.cloud.gateway.routes[1].id=auth-socket-service
spring.cloud.gateway.routes[1].uri=${AUTH_SOCKET_URL}
spring.cloud.gateway.routes[1].predicates[0]=Path=/ws/**
