server.port=8083
spring.application.name=api-gateway

# Configuração Global de CORS para o ReactJS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=${FRONTEND_URL:http://localhost:5173,http://localhost}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[4]=PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[5]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

# Rota para a API de Autenticação
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Rota para a API de Gerenciamento de Tarefas
spring.cloud.gateway.routes[1].id=task-service
spring.cloud.gateway.routes[1].uri=${TASK_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/tasks/**